name: "Update anki version"

on:
  # run workflow every monday at 00:00 UTC
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-version:
    name: Update anki version

    runs-on: blacksmith-4vcpu-ubuntu-2404

    # add GH token to secrets as GH_UPDATE_ANKI
    # with write access to repository
    # to allow workflow to write to repository
    #
    # normal GITHUB_TOKEN will not trigger the container-build workflow
    # see here: <https://stackoverflow.com/a/73489863>

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_UPDATE_ANKI }}
      - uses: mikefarah/yq@v4

      - name: Get current anki-sync-server version
        id: get-current
        run: |
          echo "version=$(yq '.env.anki_version' ./.github/workflows/build.yml)" >> $GITHUB_OUTPUT

      - name: Fetch GH API and get tag_name from latest release
        id: get-latest
        run: |
          # get latest release and extract tag_name
          tag_name=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ankitects/anki/releases/latest |\
            yq '.tag_name')

          # set output for later use
          echo "version=$tag_name" >> $GITHUB_OUTPUT

      - name: Set new anki_version
        if: ${{ steps.get-current.outputs.version != steps.get-latest.outputs.version }}
        run: |
          sed -i -E "s/^([[:space:]]*anki_version:[[:space:]]*\")[^\"]*(\")/\1${{ steps.get-latest.outputs.version }}\2/" ./.github/workflows/build.yml

      - name: Set up git email/name and commit changes
        if: ${{ steps.get-current.outputs.version != steps.get-latest.outputs.version }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./.github/workflows/build.yml
          git commit -m "BOT Bump version to ${{ steps.get-latest.outputs.version }}"
          git push origin main
